HastaneDoktorListesi/Models/Doktor.cs
namespace HastaneDoktorListesi.Models
{
    public class Doktor
    {
        public int DoktorID { get; set; }
        public string DoktorAdi { get; set; }
        public string DoktorÜnvan { get; set; }
        public string DoktorProfilResmi { get; set; }
    }
}

HastaneDoktorListesi/Controllers/DoktorController.cs
using Microsoft.AspNetCore.Mvc;
using HastaneDoktorListesi.Data;
using HastaneDoktorListesi.ViewModels;
using HastaneDoktorListesi.Models;

namespace HastaneDoktorListeleri.Controllers
{
    public class DoktorController : Controller
    {
        HastaneDBContext _context = new HastaneDBContext();
        public IActionResult Index()
        {
            _context.Database.EnsureCreated();
            return View();
        }

        public IActionResult DoktorEkle()
        {
            return View();
        }
        [HttpPost]
        
        public IActionResult DoktorEkle(DoktorEkle_VM doktor)
        {
            FileStream fs = new FileStream("wwwroot/DoktorProfilePic/" + doktor.DoktorProfilResmi.FileName, FileMode.Create);
            doktor.DoktorProfilResmi.CopyTo(fs);

            Doktor yeniDoktor = new Doktor()
            {
                DoktorAdi = doktor.DoktorAdi,
                DoktorÜnvan = doktor.DoktorÜnvan,
                DoktorProfilResmi = doktor.DoktorProfilResmi.FileName

            };


            _context.Doktorlar.Add(yeniDoktor);
            _context.SaveChanges();
            
            return RedirectToAction("DoktorlarListesi");
        }
       
        public IActionResult DoktorlarListesi()
        {
            var doktorlar = _context.Doktorlar.ToList();
            return View(doktorlar);
        }

    
        [HttpGet]
        public IActionResult DoktorDuzenle(int id)
        {
            var d = _context.Doktorlar.Find(id);
            if (d == null) return NotFound();

            var vm = new DoktorEkle_VM
            {
                DoktorID = d.DoktorID,
                DoktorAdi = d.DoktorAdi,
                DoktorÜnvan = d.DoktorÜnvan.ToString()
            };
            return View(vm);
        }

       
        [HttpPost]
        public IActionResult DoktorDuzenle(DoktorEkle_VM model)
        {
            var d = _context.Doktorlar.Find(model.DoktorID);
            if (d == null) return NotFound();

            d.DoktorAdi = model.DoktorAdi;
            d.DoktorÜnvan = model.DoktorÜnvan;

            if (model.DoktorProfilResmi != null)
            {
                string dosyaAdi = Guid.NewGuid().ToString() + Path.GetExtension(model.DoktorProfilResmi.FileName);
                string yol = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/DoktorProfilePic", dosyaAdi);

                using (var stream = new FileStream(yol, FileMode.Create))
                {
                    model.DoktorProfilResmi.CopyTo(stream);
                }
                d.DoktorProfilResmi = dosyaAdi;
            }
            _context.SaveChanges();
            return RedirectToAction("DoktorlarListesi");
        }
        public IActionResult DoktorSil(int id)
        {
            var doktor = _context.Doktorlar.Find(id);
            if (doktor != null)
            {
                _context.Doktorlar.Remove(doktor);
                _context.SaveChanges();
            }
            return RedirectToAction("DoktorlarListesi");
        }
    }
}

HastaneDoktorListesi/Controllers/HastaController.cs
using HastaneDoktorListesi.Data;
using HastaneDoktorListesi.Models;
using HastaneDoktorListesi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HastaneDoktorListesi.Controllers
{
    public class HastaController : Controller
    {
        HastaneDBContext _context = new HastaneDBContext();
        public IActionResult Index()
        {
            _context.Database.EnsureCreated();
            return View();
        }

        public IActionResult HastaListesi()
        {
            var hastalar = _context.Hastalar.Include(h => h.Doktor).Include(h => h.Hastalık) .ThenInclude(has => has.Ilac).ToList();

            return View(hastalar);
        }
        [HttpGet]
        public IActionResult HastaEkle()
        {
            var vm = new HastaEkle_VM
            {
                DoktorListesi = _context.Doktorlar.Select(d => new SelectListItem
                {
                    Value = d.DoktorID.ToString(),
                    Text = d.DoktorAdi
                }).ToList(),

                HastalikListesi = _context.Hastaliklar.Select(h => new SelectListItem
                {
                    Value = h.HastalikID.ToString(),
                    Text = h.HastalikAd
                }).ToList()
            };
            return View(vm);
        }
        [HttpPost]
        public IActionResult HastaEkle(HastaEkle_VM model)
        {
            string dosyaAdi = "default.png";
            if (model.HastaProfilResmi != null)
            {
                dosyaAdi = Guid.NewGuid().ToString() + Path.GetExtension(model.HastaProfilResmi.FileName);
                string yol = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/HastaProfilePic", dosyaAdi);
                using (var stream = new FileStream(yol, FileMode.Create)) { model.HastaProfilResmi.CopyTo(stream); }
            }

            var yeniHasta = new Hasta
            {
                HastaAd = model.HastaAd,
                HastaProfilResmi = dosyaAdi,
                DoktorID = model.DoktorID,
                HastalıkID = model.HastalıkID
            };

            _context.Hastalar.Add(yeniHasta);
            _context.SaveChanges();
            return RedirectToAction("HastaListesi");
        }

        [HttpGet]
        public IActionResult HastaGuncelle(int id)
        {
            var hasta = _context.Hastalar.Find(id);
            if (hasta == null) return NotFound();

            var vm = new HastaEkle_VM
            {
                HastaID = hasta.HastaID,
                HastaAd = hasta.HastaAd,
                DoktorID = hasta.DoktorID,
                HastalıkID = hasta.HastalıkID,

                HastalikListesi = _context.Hastaliklar.Select(h => new SelectListItem
                {
                    Value = h.HastalikID.ToString(),
                    Text = h.HastalikAd
                }).ToList(),

                DoktorListesi = _context.Doktorlar.Select(d => new SelectListItem
                {
                    Value = d.DoktorID.ToString(),
                    Text = d.DoktorAdi
                }).ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult HastaGuncelle(HastaEkle_VM model)
        {
            
            if (model.HastaProfilResmi == null)
            {
                ModelState.Remove("HastaProfilResmi");
            }

            if (ModelState.IsValid)
            {
                var guncellenecek = _context.Hastalar.Find(model.HastaID);
                if (guncellenecek != null)
                {
                    guncellenecek.HastaAd = model.HastaAd;
                    guncellenecek.DoktorID = model.DoktorID;
                    guncellenecek.HastalıkID = model.HastalıkID;

                    
                    if (model.HastaProfilResmi != null)
                    {
                        string dosyaAdi = Guid.NewGuid().ToString() + Path.GetExtension(model.HastaProfilResmi.FileName);
                        string yol = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/HastaProfilePic", dosyaAdi);
                        using (var stream = new FileStream(yol, FileMode.Create))
                        {
                            model.HastaProfilResmi.CopyTo(stream);
                        }
                        guncellenecek.HastaProfilResmi = dosyaAdi;
                    }

                    _context.SaveChanges();
                    return RedirectToAction("HastaListesi");
                }
            }

           
            model.HastalikListesi = _context.Hastaliklar.Select(h => new SelectListItem
            {
                Value = h.HastalikID.ToString(),
                Text = h.HastalikAd
            }).ToList();

            model.DoktorListesi = _context.Doktorlar.Select(d => new SelectListItem
            {
                Value = d.DoktorID.ToString(),
                Text = d.DoktorAdi
            }).ToList();

            return View(model);
        }

        public IActionResult HastaSil(int id)
        {
            var hasta = _context.Hastalar.Find(id);
            if (hasta != null)
            {
                _context.Hastalar.Remove(hasta);
                _context.SaveChanges();
            }
            return RedirectToAction("HastaListesi");
        }
    }
}

HastaneDoktorListesi/Controllers/HastalikController.cs
using HastaneBilgiListeleri.Models;
using HastaneBilgiListeleri.ViewModels;
using HastaneDoktorListesi.Data;
using HastaneDoktorListesi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

public class HastalikController : Controller
{
    HastaneDBContext _context = new HastaneDBContext();

  
    public IActionResult HastalıkListesi()
    {
        var liste = _context.Hastaliklar.Include(h => h.Ilac).ToList();
        return View(liste);
    }

    [HttpGet]
    public IActionResult HastalıkEkle() {
        var vm = new HastalikEkle_VM
        {
            IlacListesi = _context.Ilaclar.Select(i => new SelectListItem
            {
                Value = i.IlacID.ToString(),
                Text = i.IlacAd
            }).ToList()
        };
        return View(vm);
    }

    [HttpPost]
    public IActionResult HastalıkEkle(Hastalik model)
    {
        if (!string.IsNullOrEmpty(model.HastalikAd))
        {
            var yeniHastalik = new Hastalik
            {
                HastalikAd = model.HastalikAd,
                IlacID = model.IlacID
            };
            _context.Hastaliklar.Add(model);
            _context.SaveChanges();
        }
        return RedirectToAction("HastalıkListesi");
    }

    [HttpGet]
    public IActionResult HastalıkGüncelle(int id)
    {
        var has = _context.Hastaliklar.Find(id);
        if (has == null) return NotFound();

        var vm = new HastalikEkle_VM
        {
            HastalikID = has.HastalikID,
            HastalikAd = has.HastalikAd,
            IlacID = has.IlacID,
            IlacListesi = _context.Ilaclar.Select(i => new SelectListItem
            {
                Value = i.IlacID.ToString(),
                Text = i.IlacAd
            }).ToList()
        };
        return View(vm);
    }


    [HttpPost]
    public IActionResult HastalıkGüncelle(HastalikEkle_VM model)
    {
        var guncellenecekHastalik = _context.Hastaliklar.Find(model.HastalikID);

        guncellenecekHastalik.HastalikAd = model.HastalikAd;
        guncellenecekHastalik.IlacID = model.IlacID;

        _context.SaveChanges();

        return RedirectToAction("HastalıkListesi");
            
        
    }

    public IActionResult HastalıkSil(int id)
    {
        var hastalık = _context.Hastaliklar.Find(id);
        if (hastalık != null)
        {
            _context.Hastaliklar.Remove(hastalık);
            _context.SaveChanges();
        }
        return RedirectToAction("HastalıkListesi");
    }
}

HastaneDoktorListesi/Controllers/IlacController.cs
using HastaneBilgiListeleri.Models;
using HastaneDoktorListesi.Data;
using HastaneDoktorListesi.Models;
using Microsoft.AspNetCore.Mvc;

public class IlacController : Controller
{
    HastaneDBContext _context = new HastaneDBContext();

    public IActionResult IlacListesi() => View(_context.Ilaclar.ToList());

    [HttpGet]
    public IActionResult IlacEkle() => View();

    [HttpPost]
    public IActionResult IlacEkle(Ilac model)
    {
        if (!string.IsNullOrEmpty(model.IlacAd))
        {
            _context.Ilaclar.Add(model);
            _context.SaveChanges();
        }
        return RedirectToAction("IlacListesi");
    }

    [HttpGet]
    public IActionResult IlacGuncelle(int id)
    {
        var ilac = _context.Ilaclar.Find(id);
        if (ilac == null) return NotFound();
        return View(ilac);
    }

    [HttpPost]
    public IActionResult IlacGuncelle(Ilac model)
    {
        var ilac = _context.Ilaclar.Find(model.IlacID);
        if (ilac != null)
        {
            ilac.IlacAd = model.IlacAd;
            _context.SaveChanges();
        }
        return RedirectToAction("IlacListesi");
    }

    public IActionResult IlacSil(int id)
    {
        var ilac = _context.Ilaclar.Find(id);
        if (ilac != null)
        {
            _context.Ilaclar.Remove(ilac);
            _context.SaveChanges();
        }
        return RedirectToAction("IlacListesi");
    }
}

HastaneDoktorListesi/Views/Doktor/DoktorDuzenle.cshtml
@using HastaneDoktorListesi.ViewModels
@model DoktorEkle_VM

<div class="hospital-container">
    <div class="hospital-card shadow">
        <h3 class="hospital-header">Doktor Düzenle</h3>
        <form asp-action="DoktorDuzenle" method="post" enctype="multipart/form-data" class="p-4">
            <input type="hidden" asp-for="DoktorID" />
            <div class="mb-3">
                <label class="form-label fw-bold">Doktor Adı</label>
                <input asp-for="DoktorAdi" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label fw-bold">Ünvan</label>
                <select asp-for="DoktorÜnvan" class="form-select">
                    <option value="" disabled>Ünvan Seçiniz...</option>
                    <option value="Pratisyen Hekim">Pratisyen Hekim</option>
                    <option value="Uzman Doktor">Uzman Doktor</option>
                    <option value="Operatör Doktor">Operatör Doktor</option>
                    <option value="Yardımcı Doçent">Yardımcı Doçent</option>
                    <option value="Doçent Doktor">Doçent Doktor</option>
                    <option value="Profesör Doktor">Profesör Doktor</option>
                </select>
            </div>
            <div class="mb-3">
                <label class="form-label fw-bold">Yeni Resim Seç</label>
                <input type="file" asp-for="DoktorProfilResmi" class="form-control" />
            </div>

            <div class="d-flex gap-2 pt-3">
                <button type="submit" class="btn-save-main flex-grow-1">Değişiklikleri Kaydet</button>
                <a asp-action="DoktorlarListesi" class="btn btn-light border flex-grow-1 text-center" style="padding:12px; border-radius:8px; text-decoration:none; color:#333;">
                    İptal / Geri Dön
                </a>
            </div>
        </form>
    </div>
</div>

HastaneDoktorListesi/Views/Doktor/DoktorEkle.cshtml
@using HastaneDoktorListesi.ViewModels
@model DoktorEkle_VM

<div class="hospital-card">
    <div class="hospital-card-header">
        <i class="medical-icon">✚</i>
        <h2>Doktor Kayıt Paneli</h2>
        <p>Lütfen yeni doktor bilgilerini eksiksiz giriniz.</p>
    </div>

    <form method="post" asp-action="DoktorEkle" enctype="multipart/form-data" class="hospital-form">
        <div class="input-group">
            <label asp-for="DoktorAdi">Tam Adı ve Soyadı</label>
            <input asp-for="DoktorAdi" placeholder="Örn: Dr. Ahmet Yılmaz" />
        </div>

        <div class="input-group">
            <label asp-for="DoktorÜnvan">Tıbbi Ünvan</label>
            <select asp-for="DoktorÜnvan">
                <option value="" disabled selected>Ünvan Seçiniz...</option>
                <option value="Pratisyen Hekim">Pratisyen Hekim</option>
                <option value="Uzman Doktor">Uzman Doktor</option>
                <option value="Operatör Doktor">Operatör Doktor</option>
                <option value="Yardımcı Doçent">Yardımcı Doçent</option>
                <option value="Doçent Doktor">Doçent Doktor</option>
                <option value="Profesör Doktor">Profesör Doktor</option>
            </select>
        </div>

        <div class="input-group">
            <label asp-for="DoktorProfilResmi">Profil Fotoğrafı</label>
            <div class="file-upload-wrapper">
                <input type="file" asp-for="DoktorProfilResmi" />
                <small>PNG veya JPG (Maks. 2MB)</small>
            </div>
        </div>

        <div class="d-grid gap-2">
            <button type="submit" class="btn-hospital">
                <span>Sisteme Kaydet</span>
            </button>
            <a asp-action="DoktorlarListesi" class="btn-cancel text-center" style="text-decoration:none; display:block; margin-top:10px; color:#666; font-size:0.9rem;">
                ✕ Vazgeç ve Listeye Dön
            </a>
        </div>
    </form>
</div>

HastaneDoktorListesi/Views/Doktor/DoktorlarListesi.cshtml
@model List<Doktor>
<div class="hospital-nav-bar shadow-sm">
    <a asp-controller="Doktor" asp-action="DoktorlarListesi" class="nav-quick-link"><i class="fas fa-user-md"></i> Doktorlar</a>
    <a asp-controller="Hasta" asp-action="HastaListesi" class="nav-quick-link"><i class="fas fa-user-injured"></i> Hastalar</a>
    <a asp-controller="Hastalik" asp-action="HastalıkListesi" class="nav-quick-link"><i class="fas fa-microscope"></i> Hastalıklar</a>
    <a asp-controller="Ilac" asp-action="IlacListesi" class="nav-quick-link"><i class="fas fa-pills"></i> İlaçlar</a>
</div>
<div class="hospital-container">
    <div class="d-flex justify-content-between">
        <h2 class="hospital-header">Doktor Listesi</h2>
        <a asp-action="DoktorEkle" class="btn btn-primary">Yeni Ekle</a>
    </div>
    <table class="table-custom">
        <thead>
            <tr> <th>Profil</th> <th>Ad Soyad</th> <th>Ünvan</th> <th>İşlemler</th> </tr>
        </thead>
        <tbody>
            @foreach (var d in Model)
            {
                <tr>
                    <td><img src="~/DoktorProfilePic/@d.DoktorProfilResmi" class="doctor-thumb" /></td>
                    <td>@d.DoktorAdi</td>
                    <td>@d.DoktorÜnvan</td>
                    <td>
                        <a asp-action="DoktorDuzenle" asp-route-id="@d.DoktorID" class="text-warning">Düzenle</a> |
                        <a asp-action="DoktorSil" asp-route-id="@d.DoktorID" class="text-danger" onclick="return confirm('Silinsin mi?')">Sil</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

HastaneDoktorListesi/Views/Doktor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}